### PR TITLE
Fix order values when opening a note

### LINKED ISSUE #15: App Crash When Importing Notes and Opening a Task Note
The application crashes when attempting to import notes and opening a task note.

Log

```
type: crash
osVersion: google/husky/husky:14/AP2A.240905.003/2024092900:user/release-keys
package: com.omgodse.notally:55
process: com.omgodse.notally
processUptime: 1526 + 50 ms
installer: com.android.packageinstaller
 
java.lang.NullPointerException
at com.omgodse.notally.recyclerview.ListItemNoSortCallback.compare(ListItemNoSortCallback.kt:15)
at com.omgodse.notally.recyclerview.ListItemNoSortCallback.compare(ListItemNoSortCallback.kt:7)
at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
at java.util.TimSort.sort(TimSort.java:220)
at java.util.Arrays.sort(Arrays.java:1270)
at androidx.recyclerview.widget.SortedList.sortAndDedup(SortedList.java:358)
at androidx.recyclerview.widget.SortedList.addAllInternal(SortedList.java:256)
at androidx.recyclerview.widget.SortedList.addAll(SortedList.java:168)
at androidx.recyclerview.widget.SortedList.addAll(SortedList.java:194)
at com.omgodse.notally.activities.MakeList.setStateFromModel(MakeList.kt:112)
at com.omgodse.notally.activities.NotallyActivity$onCreate$1.invokeSuspend(NotallyActivity.kt:100)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:365)
at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
at kotlinx.coroutines.BuildersKt.launch(Unknown Source:1)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source:1)
at com.omgodse.notally.activities.NotallyActivity.onCreate(NotallyActivity.kt:84)
at android.app.Activity.performCreate(Activity.java:9013)
at android.app.Activity.performCreate(Activity.java:8991)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1531)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3986)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4184)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:114)
at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2602)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8623)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:894)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@231851f, Dispatchers.Main.immediate]
```

### PR DESCRIPTION
**Pull request by PhilKes**
This should fix #15 

* When a Task/List note is opened, `null` `order` values as well as duplicate `order` values are fixed

### CODE REVIEW

**Comment by PhilKes** [comment]
@CodeNomadHQ if you could test it out with your notes that would be great :+1:

**Comment by CodeNomadHQ** [comment]
Great, now it works for opening the note.

**Comment by PhilKes** [comment]
> Great, now it works for opening the note but importing subtasks still don’t work.

Can you provide the backup `.zip` that doesnt work? I just tested it again and had no problems exporting a note and re-importing it with the correct subtasks present

**Comment by CodeNomadHQ** [comment]
I only have my personal notes backup that I used for testing, but I don’t think it matters too much since I added those subtasks earlier. I tested exporting and importing notes now, and it worked fine.

**Pull request merged**
