### PR TITLE
Support adding any files as attachments

### LINKED ISSUE #8: File attachment
What kept me away from the original no itally is that it does not support files as attachments.
Please consider  adding this feature

### PR DESCRIPTION
**Pull request by PhilKes**
Closes #8 
* Adds `Attach file` option in the toolbar menu 
* Attached files are displayed as chips:
* If there are many file attachments you can horizontally scroll the attached files' chips
* If you click on an attached file's chip it will open the file in a suiting external app
* Attached files are backed up in the `.zip` files

[notally_file_attachments.webm](https://github.com/user-attachments/assets/3bcacb9e-fa37-45a5-ae7c-75e9ef777666)

TODO:
- [x] Add automatic migration from old backups
- [x] Add possibility to remove attached files (probably long-click on an attached file name with popup to delete it)
- [x] After a file is attached it is not immediately shown in the edit note activity
- [x] ~~In general add Unit Tests for Import/Export~~

### CODE REVIEW

**Comment by CodeNomadHQ** [comment]
A bit off-topic, but are you open to a voice chat? I have a few questions about some issues I'm having with Android Studio, as well as what's being added and the UI rework.

**Comment by PhilKes** [comment]
> A bit off-topic, but are you open to a voice chat? I have a few questions about some issues I'm having with Android Studio, as well as what's being added and the UI rework.

Not really atm, but perhaps we can chat on discord to make it easier: phil4510

**Comment by PhilKes** [comment]
@ippocratis I changed the UI a bit, is that how you imagined it?

**Comment by ippocratis** [comment]
> @ippocratis I changed the UI a bit, is that how you imagined it?

Yes its perfect

You can see from the navigator that the note contains filea,you can view the filename,open the files in external app and also delete them .

**Comment by PhilKes** [comment]
> > @ippocratis I changed the UI a bit, is that how you imagined it?
> 
> Yes its perfect
> 
> You can see from the navigator that the note contains files,you can view the filename,open the files in external app and also delete them .

Great!
I released the current master as [v6.0-RC1](https://github.com/PhilKes/Notally/releases/tag/v6.0-RC1)
There shouldnt be any compatibility issues, but I had to add a database migration for the files attachment to the notes, so if something comes up just add a new bug issue

**Comment by ippocratis** [comment]
@PhilKes I'm getting invalid package when I try to install it.

Uninstalled the old apk

Android 14 custom rom

**Comment by PhilKes** [comment]
> @PhilKes I'm getting invalid package when I try to install it.
> 
> Uninstalled the old apk
> 
> Android 14 custom rom
> 
> I have root so can directly execute pm commands in terminal.
> 
> Here what the package manager throws if it helps
> 
> sudo pm install Notally-6.0-RC1.apk Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl87240160.tmp/base.apk: Attempt to get length of null array]
> 
> I guess its not signed
> 
> I managed to sign it with
> 
> keytool
> 
> keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias
> 
> And appsigner
> 
> sudo apksigner sign --ks my-release-key.jks --out signed_notally.apk Notally-6.0-RC1.apk
> 
> But needs root
> 
> After that it insatlls

Ah yeah its not signed, I think its no problem if your phone is set to allow unknown sources, but not sure. Will add signed apks soon

**Pull request merged**
